import type { Resource } from "./types";

/** Sample resources for initial UI — will be replaced by Supabase queries */
export const SAMPLE_RESOURCES: (Resource & { formats: string[] })[] = [
  {
    id: 1, title: "Safeguarding Policy Toolkit for Grassroots Clubs", slug: "safeguarding-toolkit",
    description: "A comprehensive toolkit for grassroots sport clubs to develop, implement and monitor safeguarding policies.",
    abstract: "A comprehensive toolkit for grassroots sport clubs to develop, implement and monitor safeguarding policies. Covers policy templates, training modules and implementation guides.",
    resource_type: "Toolkit", topics: ["Safeguarding"], sports: ["Football"],
    target_audiences: ["coach", "club_manager"], project_name: "SafeClub 2024",
    funding_source: "Erasmus+ Sport KA2", partner_countries: ["ES", "DE", "TR"],
    project_year: 2024, languages: ["EN", "ES", "DE", "TR"], license: "CC BY-SA 4.0",
    page_count: 80, status: "published", featured: true,
    view_count: 2340, download_count: 890, rating_avg: 4.7, rating_count: 34, applied_count: 34,
    submitted_by: null, published_at: "2024-06-15", created_at: "2024-05-01",
    formats: ["PDF", "Video", "Infographic"],
  },
  {
    id: 2, title: "AI-Powered Adaptive Learning for Coach Education", slug: "ai-coach-education",
    description: "Research report on implementing AI-driven personalized learning pathways in coach education.",
    abstract: "Research report on implementing AI-driven personalized learning pathways in coach education. Includes case studies from Netherlands and Norway.",
    resource_type: "Report", topics: ["AI & Education"], sports: ["Multi-sport"],
    target_audiences: ["educator", "coach"], project_name: "COMPATH 2",
    funding_source: "Erasmus+ Sport KA2", partner_countries: ["NL", "NO"],
    project_year: 2025, languages: ["EN", "NO", "NL"], license: "CC BY 4.0",
    page_count: 120, status: "published", featured: false,
    view_count: 1890, download_count: 654, rating_avg: 4.5, rating_count: 18, applied_count: 18,
    submitted_by: null, published_at: "2025-01-20", created_at: "2024-11-01",
    formats: ["PDF", "Practitioner Brief"],
  },
  {
    id: 3, title: "Dual Career Support: Athlete-Student Balance Guide", slug: "dual-career-guide",
    description: "Practical guide for athletes, coaches and university administrators on balancing sport with studies.",
    abstract: "Practical guide for athletes, coaches and university administrators on balancing sport with studies. Based on research across Italy, Belgium and Finland.",
    resource_type: "Guide", topics: ["Dual Career"], sports: ["Athletics"],
    target_audiences: ["athlete", "educator"], project_name: "EAS Network",
    funding_source: "Erasmus+ Sport KA2", partner_countries: ["IT", "BE", "FI"],
    project_year: 2024, languages: ["EN", "IT", "FI", "FR"], license: "CC BY 4.0",
    page_count: 45, status: "published", featured: true,
    view_count: 3120, download_count: 1450, rating_avg: 4.8, rating_count: 52, applied_count: 52,
    submitted_by: null, published_at: "2024-09-10", created_at: "2024-07-15",
    formats: ["PDF", "Micro-learning", "Quiz"],
  },
  {
    id: 4, title: "Green Sport Management: Carbon Footprint Toolkit", slug: "green-sport-toolkit",
    description: "Tools for sport organizations to measure, reduce and report their environmental footprint.",
    abstract: "Tools for sport organizations to measure, reduce and report their environmental footprint. Includes carbon calculator app and reporting templates.",
    resource_type: "Toolkit", topics: ["Green Sport"], sports: ["Multi-sport"],
    target_audiences: ["club_manager"], project_name: "GAMES Erasmus+",
    funding_source: "Erasmus+ Sport KA2", partner_countries: ["DE", "SE"],
    project_year: 2025, languages: ["EN", "DE", "SV"], license: "CC BY-SA 4.0",
    page_count: 60, status: "published", featured: false,
    view_count: 1560, download_count: 520, rating_avg: 4.3, rating_count: 12, applied_count: 12,
    submitted_by: null, published_at: "2025-02-01", created_at: "2024-12-01",
    formats: ["PDF", "App", "Video"],
  },
  {
    id: 5, title: "Inclusive Sport Innovation Lab: Disability & Access", slug: "inclusive-sport-lab",
    description: "Interactive platform with adapted training methodologies and policy frameworks for accessible sport.",
    abstract: "Interactive platform with adapted training methodologies and policy frameworks for accessible sport. Covers physical, intellectual and sensory disabilities.",
    resource_type: "Platform", topics: ["Inclusive Sport"], sports: ["Multi-sport"],
    target_audiences: ["coach", "club_manager", "policy_maker"], project_name: "SportAccess+",
    funding_source: "Erasmus+ Sport KA2", partner_countries: ["PT", "PL", "IE"],
    project_year: 2024, languages: ["EN", "PT", "PL"], license: "CC BY 4.0",
    page_count: 95, status: "published", featured: true,
    view_count: 2780, download_count: 980, rating_avg: 4.9, rating_count: 41, applied_count: 41,
    submitted_by: null, published_at: "2024-11-05", created_at: "2024-08-20",
    formats: ["Platform", "PDF", "Video"],
  },
  {
    id: 6, title: "Padel Development Framework for Europe", slug: "padel-framework",
    description: "Strategic framework for developing padel across European countries.",
    abstract: "Strategic framework for developing padel across European countries. Covers infrastructure, coaching, competition and governance recommendations.",
    resource_type: "Report", topics: ["Sport Development"], sports: ["Padel"],
    target_audiences: ["policy_maker", "club_manager"], project_name: "PADEL-EURO",
    funding_source: "Erasmus+ Sport KA2", partner_countries: ["ES", "TR", "SE"],
    project_year: 2026, languages: ["EN", "ES", "TR", "SV"], license: "CC BY 4.0",
    page_count: 55, status: "published", featured: false,
    view_count: 1230, download_count: 410, rating_avg: 4.4, rating_count: 8, applied_count: 8,
    submitted_by: null, published_at: "2026-01-15", created_at: "2025-10-01",
    formats: ["PDF", "Infographic"],
  },
];
